---
name: Run Simkube Simulation

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:

jobs:
  simulate:
    uses: acrlabs/simkube-ci-action/.github/workflows/run.yml
    with:
      simulation-name: test-sim
      github-pat: ${{ secrets.GITHUB_PAT }}
      trace-file: ./path/to/your/trace

      instance-type: t3.xlarge
      simulation-duration: +5m
    secrets: inherit
