---
name: Launch Simkube Runner
description: Launches a pre-configured GitHub Actions runnner in EC2

inputs:
  ami-id:
    description: AMI ID for SimKube Runner AMI
    required: true

  instance-type:
    description: EC2 instance type
    required: false
    default: c7a.2xlarge

  aws-region:
    description: AWS region to launch in
    required: true

  subnet-id:
    description: Subnet ID
    required: true

  security-group-ids:
    description: Space-separated security group IDs
    required: true

  runner-labels:
    description: Additional labels for the runner (comma-separated)
    required: false
    default: simkube,ephemeral

  simkube-runner-pat:
    description: GitHub Personal Access Token with repo scope
    required: true

  aws-access-key-id:
    description: AWS access key ID
    required: true

  aws-secret-access-key:
    description: AWS secret access key
    required: true

runs:
  using: composite
  steps:
    - name: Launch EC2 instance
      id: launch
      shell: bash
      run: "$GITHUB_ACTION_PATH/scripts/launch-ephemeral-runner.sh"
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        SIMKUBE_RUNNER_PAT: ${{ inputs.simkube-runner-pat }}
        REPO_URL: "https://github.com/${{ github.repository }}"
        RUNNER_LABELS: "${{ inputs.runner-labels }}"
        SIMKUBE_RUNNER_NAME: "github-runner-${{ github.run_id }}"
        AWS_REGION: ${{ inputs.aws-region }}
        AMI_ID: ${{ inputs.ami-id }}
        INSTANCE_TYPE: ${{ inputs.instance-type }}
        SUBNET_ID: ${{ inputs.subnet-id }}
        SECURITY_GROUP_IDS: ${{ inputs.security-group-ids }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_REPOSITORY: ${{ github.repository }}
