---
name: Launch Simkube Runner
description: Launches a pre-configured GitHub Actions runnner in EC2

inputs:
  ami-id:
    description: AMI ID for SimKube Runner AMI
    required: true

  instance-type:
    description: EC2 instance type
    required: false
    default: c7a.2xlarge

  aws-region:
    description: AWS region to launch in
    required: true

  subnet-id:
    description: Subnet ID
    required: true

  security-group-ids:
    description: Space-separated security group IDs
    required: true

  runner-labels:
    description: Additional labels for the runner (comma-separated)
    required: false
    default: simkube,ephemeral

  simkube-runner-pat:
    description: GitHub Personal Access Token with repo scope
    required: true

  aws-access-key-id:
    description: AWS access key ID
    required: true

  aws-secret-access-key:
    description: AWS secret access key
    required: true

outputs:
  instance-id:
    description: EC2 instance ID for runner that was launched
    value: ${{ steps.launch.outputs.instance-id }}

runs:
  using: composite
  steps:
    - name: Validate inputs
      shell: bash
      run: ./scripts/validate-inputs.sh
      env:
        AMI_ID: ${{ inputs.ami-id }}
        SIMKUBE_RUNNER_PAT: ${{ inputs.simkube-runner-pat }}
        AWS_ACCESS_KEY_ID: ${{ secrets.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-secret-access-key }}

    - name: Generate runner registration token
      id: token
      shell: bash
      run: ./scripts/generate-token.sh
      env:
        SIMKUBE_RUNNER_PAT: ${{ inputs.simkube-runner-pat }}
        GITHUB_REPOSITORY: ${{ github.repository }}

    - name: Launch EC2 instance
      id: launch
      shell: bash
      run: ./scripts/launch-ephemeral-runner.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        REPO_URL: "https://github.com/${{ github.repository }}"
        RUNNER_LABELS: "${{ inputs.runner-labels }}"
        EPHEMERAL_RUNNER_NAME: "runner-${{ github.run_id }}"
        RUNNER_TOKEN: "${{ steps.token.outputs.token }}"
        AWS_REGION: ${{ inputs.aws-region }}
        AMI_ID: ${{ inputs.ami-id }}
        INSTANCE_TYPE: ${{ inputs.instance-type }}
        SUBNET_ID: ${{ inputs.subnet-id }}
        SECURITY_GROUP_IDS: ${{ inputs.security-group-ids }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_REPOSITORY: ${{ github.repository }}

    - name: Wait for instance to be running and runner to register
      shell: bash
      run: ./scripts/.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        INSTANCE_ID: ${{ steps.launch.outputs.instance-id }}
        AWS_REGION: ${{ inputs.aws-region }}
        REPO: ${{ github.repository }}
        RUNNER_NAME: github-runner-${{ github.run_id }}
        GITHUB_PAT: ${{ secrets.SIMKUBE_RUNNER_PAT }}

    - name: Summary
      shell: bash
      if: success()
      run: |
        echo "Runner Launch Successful"
        echo "Instance ID: ${{ steps.launch.outputs.instance-id }}"
        echo "Runner Name: ${{ steps.userdata.outputs.runner-name }}"
        echo "Region: ${{ inputs.aws-region }}"
        echo "Instance Type: ${{ inputs.instance-type }}"
        echo ""
        echo "The runner is now available for jobs with labels: ${{ inputs.runner-labels }}"
        echo "The runner will automatically terminate after completing one job (ephemeral mode)."
