---
name: Run Simkube Simulation
description: Runs a simkube simulation on an ephemeral runner

inputs:
  simulation-name:
    description: Name of the simulation to run
    required: true

  trace-path:
    description: Path to the trace file
    required: true

  duration:
    description: Simulation duration
    required: false

  speed:
    description: Simulation speed
    required: false

runs:
  using: composite
  steps:
    - name: Run simulation
      id: build-cmd
      shell: bash
      env:
        PATH: "/home/ubuntu/.cargo/bin:$PATH"  # we should add cargo/bin to PATH in the AMI
        SIMULATION_NAME: ${{ inputs.simulation-name }}
        TRACE_PATH: ${{ inputs.trace-path }}
        DURATION: ${{ inputs.duration }}
        SPEED: ${{ inputs.speed }}
      run: |
        # Function to add optional flags
        add_flag() {
          if [ -n "$2" ]; then
            CMD="$CMD --$1 '$2'"
          fi
        }

        # Base command
        CMD="skctl run --disable-metrics '$SIMULATION_NAME'"

        # Required
        CMD="$CMD --trace-path '$TRACE_PATH'"

        # Add optional flags
        add_flag "speed" "$SPEED"
        add_flag "duration" "$DURATION"

        echo ""
        echo "Command to execute:"
        echo "$CMD"
        echo ""
        echo "Starting simulation..."
        eval $CMD

    - name: Wait for simulation to start
      shell: bash
      env:
        SIMULATION_NAME: ${{ inputs.simulation-name }}
      run: |
        echo "Waiting for simulation to reach Running state..."
        kubectl wait --for=condition=Running simulation/"$SIMULATION_NAME"
        echo "✓ Simulation is running!"

    - name: Wait for simulation to complete
      shell: bash
      env:
        SIMULATION_NAME: ${{ inputs.simulation-name }}
      run: |
        echo "Waiting for simulation to complete..."
        kubectl wait --for=condition=Finished simulation/"$SIMULATION_NAME"
        echo "✓ Simulation completed successfully!"

    - name: Display summary
      shell: bash
      env:
        SIMULATION_NAME: ${{ inputs.simulation-name }}
      if: success()
      run: |
        echo ""
        echo "Simulation Completed!"
        echo ""
        echo "Name:          '$SIMULATION_NAME'"
        echo "Completed at:  $(date)"
        echo ""
