---
name: Run Simkube Simulation
description: Runs a simkube simulation on an ephemeral runner

inputs:
  simulation-name:
    description: Name of the simulation to run
    required: true

  trace-path:
    description: Path to the trace file
    required: true

  duration:
    description: Simulation duration
    required: false

  speed:
    description: Simulation speed
    required: false

runs:
  using: composite
  steps:
    - name: Run simulation
      id: build-cmd
      shell: bash
      run: "$GITHUB_ACTION_PATH/scripts/run-simulation.sh"
      env:
        SIMULATION_NAME: ${{ inputs.simulation-name }}
        TRACE_PATH: ${{ inputs.trace-path }}
        DURATION: ${{ inputs.duration }}
        SPEED: ${{ inputs.speed }}

    - name: Collect failure information
      shell: bash
      run: "$GITHUB_ACTION_PATH/scripts/failure-summary.sh"
      env:
        SIMULATION_NAME: ${{ inputs.simulation-name }}
      if: failure()
